In [38]:
import pandas as pd
import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [39]:
messages=pd.read_csv('spam.csv',sep='\t',names=['label','message'])

In [40]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [41]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [42]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## train test split nefre bow

In [43]:
# output feature
y=pd.get_dummies(messages['label']).astype('int')
y # 1 for ham and 0 for spam
y=y.iloc[:,0].values
y.shape

(5572,)

In [44]:
## train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.2, random_state=0)

## bag of words ##

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500, ngram_range=(1,2))
# X=cv.fit_transform(corpus).toarray()

In [47]:
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [48]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [49]:
X_train.shape, X_test.shape


((4457, 2500), (1115, 2500))

In [50]:
cv.vocabulary_

{'good': np.int64(841),
 'movi': np.int64(1381),
 'ok': np.int64(1488),
 'leav': np.int64(1140),
 'free': np.int64(735),
 'give': np.int64(806),
 'otherwis': np.int64(1529),
 'someth': np.int64(1937),
 'mayb': np.int64(1291),
 'bit': np.int64(185),
 'hope': np.int64(974),
 'got': np.int64(856),
 'home': np.int64(970),
 'babe': np.int64(139),
 'still': np.int64(1989),
 'awak': np.int64(130),
 'sinc': np.int64(1899),
 'alreadi': np.int64(57),
 'workin': np.int64(2433),
 'get': np.int64(790),
 'job': np.int64(1066),
 'said': np.int64(1791),
 'matter': np.int64(1283),
 'mind': np.int64(1325),
 'say': np.int64(1806),
 'oh': np.int64(1485),
 'yeah': np.int64(2476),
 'diet': np.int64(543),
 'oh yeah': np.int64(1487),
 'sorri': np.int64(1947),
 'thing': np.int64(2108),
 'may': np.int64(1290),
 'pub': np.int64(1673),
 'later': np.int64(1122),
 'ill': np.int64(1013),
 'call': np.int64(255),
 'even': np.int64(641),
 'idea': np.int64(1007),
 'dear': np.int64(511),
 'reach': np.int64(1704),
 'room'

In [51]:
from sklearn.naive_bayes import MultinomialNB
bow_model=MultinomialNB()
bow_model.fit(X_train,y_train)
bow_model

MultinomialNB()

In [52]:
y_pred=bow_model.predict(X_test)

In [53]:
y_pred

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [54]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("accuracy score: ", accuracy_score(y_test,y_pred))
print("confusion matrix: \n", confusion_matrix(y_test,y_pred))
print("classification report: ", classification_report(y_test,y_pred))

accuracy score:  0.9856502242152466
confusion matrix: 
 [[149  11]
 [  5 950]]
classification report:                precision    recall  f1-score   support

           0       0.97      0.93      0.95       160
           1       0.99      0.99      0.99       955

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



## tfidf model ##

In [55]:
## train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.2, random_state=0)

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()
len(X_train), len(X_test)

(4457, 1115)

In [57]:
tv.vocabulary_

{'good': np.int64(841),
 'movi': np.int64(1381),
 'ok': np.int64(1488),
 'leav': np.int64(1140),
 'free': np.int64(735),
 'give': np.int64(806),
 'otherwis': np.int64(1529),
 'someth': np.int64(1937),
 'mayb': np.int64(1291),
 'bit': np.int64(185),
 'hope': np.int64(974),
 'got': np.int64(856),
 'home': np.int64(970),
 'babe': np.int64(139),
 'still': np.int64(1989),
 'awak': np.int64(130),
 'sinc': np.int64(1899),
 'alreadi': np.int64(57),
 'workin': np.int64(2433),
 'get': np.int64(790),
 'job': np.int64(1066),
 'said': np.int64(1791),
 'matter': np.int64(1283),
 'mind': np.int64(1325),
 'say': np.int64(1806),
 'oh': np.int64(1485),
 'yeah': np.int64(2476),
 'diet': np.int64(543),
 'oh yeah': np.int64(1487),
 'sorri': np.int64(1947),
 'thing': np.int64(2108),
 'may': np.int64(1290),
 'pub': np.int64(1673),
 'later': np.int64(1122),
 'ill': np.int64(1013),
 'call': np.int64(255),
 'even': np.int64(641),
 'idea': np.int64(1007),
 'dear': np.int64(511),
 'reach': np.int64(1704),
 'room'

In [58]:
from sklearn.naive_bayes import MultinomialNB
tfidf_model=MultinomialNB()
tfidf_model.fit(X_train,y_train)
tfidf_model

MultinomialNB()

In [59]:
y_pred=tfidf_model.predict(X_test)

In [60]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("accuracy score: ", accuracy_score(y_test,y_pred))
print("confusion matrix: \n", confusion_matrix(y_test,y_pred))
print("classification report: ", classification_report(y_test,y_pred))

accuracy score:  0.9775784753363229
confusion matrix: 
 [[135  25]
 [  0 955]]
classification report:                precision    recall  f1-score   support

           0       1.00      0.84      0.92       160
           1       0.97      1.00      0.99       955

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

